ALTER TABLE "products" ADD COLUMN "beschreibung" text;
--> statement-breakpoint

UPDATE "products" SET "beschreibung" = 'Diese Tischlampe entstand aus einem über hundert Jahre alten Eichenbalken, der einst Teil eines Bauernhofes in der Nähe von Klosterneuburg war. Das Holz wurde sorgfältig von Hand geschliffen, geölt und auf Schäden untersucht — Risse und Astlöcher bleiben bewusst erhalten, denn sie erzählen die Geschichte des Materials. Der warmweiße Edison-Glühfaden taucht jeden Raum in ein weiches, bernsteinfarbenes Licht, das an offene Kamine und ruhige Abende erinnert. Die Lampenfassung ist aus mattiertem Messing gefertigt und harmoniert mit den goldenen Tönen des Eichenholzes. Kein Stück gleicht dem anderen — jede Maserung, jede Jahresring-Linie ist einzigartig.' WHERE "id" = 1;

UPDATE "products" SET "beschreibung" = 'Die Wandlampe No.2 vereint rustikalen Charme mit klarer Linienführung. Der Korpus ist aus altem Fichtenholz gefertigt, das seinen silbrigen Patina-Ton durch jahrzehntelange Witterung im Freien erhalten hat. Montiert wird sie mit zwei Edelstahlschrauben direkt an der Wand — die Verkabelung verläuft verdeckt im Korpus. Das Licht fällt weich nach unten und seitlich, ideal als Leselampe am Bett oder als stimmungsvolle Wandbeleuchtung im Flur. Der Arm lässt sich auf Wunsch in verschiedenen Längen fertigen.' WHERE "id" = 2;

UPDATE "products" SET "beschreibung" = 'Für die Stehlampe No.3 wurde eine massive Altholzbohle aus einem abgebrochenen Stadel verwendet. Der Stamm wurde aufgetrennt, die breiteste Bohle als Fuß verarbeitet und die naturbelassene Außenkante als gestalterisches Element bewusst in das Design integriert. Die Höhe ist auf Stehlampenniveau ausgelegt — das Licht trifft den Raum von oben und schafft eine weiche Indirektbeleuchtung. Mit einem breiten Leinenschirm in Naturton wird das Licht zusätzlich gefiltert und erwärmt. Ein Statement-Stück für Wohnzimmer, Lesecken und Empfangsbereiche.' WHERE "id" = 3;

UPDATE "products" SET "beschreibung" = 'Die Hängeleuchte No.4 wurde aus einem alten Deckenbalken gefertigt, der beim Umbau eines Klosterneuburger Hauses aus dem 19. Jahrhundert abgetragen wurde. Das Holz trägt die Spuren seiner Vergangenheit: Nagellöcher, Verfärbungen und die charakteristische Textur von jahrzehntealtem Leimholz. Ideal über einem Esstisch oder einer Kücheninsel, schafft sie einen warmen, einladenden Mittelpunkt im Raum. Das Textilkabel ist in Schwarz oder Naturbeige erhältlich und lässt sich auf die gewünschte Hängehöhe einkürzen.' WHERE "id" = 4;

UPDATE "products" SET "beschreibung" = 'Die Nachttischlampe No.5 ist ein intimes, handliches Stück für ruhige Abendstunden. Das Nussholz wurde aus einem gefällten Walnussbaum aus dem Weinviertel gewonnen und zeigt die typische dunkelbraune bis cremefarbene Maserung dieser edlen Holzart. Die kompakte Form passt auf jeden Nachttisch und gibt ein warmes, gedämmtes Licht ab, das weder blendet noch stört. Das Anschlusskabel ist mit einem kleinen Inline-Schalter ausgestattet. Auf Wunsch ist auch eine Version mit USB-Ladeport erhältlich.' WHERE "id" = 5;

UPDATE "products" SET "beschreibung" = 'Die Außenleuchte No.6 ist für den dauerhaften Einsatz im Freien konzipiert — auf der Terrasse, am Hauseingang oder im Garten. Das Lärchenholz wurde mit einem speziellen Außenöl behandelt, das vor Feuchtigkeit, UV-Strahlung und Frost schützt, ohne den natürlichen Charakter des Holzes zu verdecken. Die IP44-zertifizierte Fassung macht sie wetterfest. Im Laufe der Zeit entwickelt Lärchenholz im Freien eine silbergraue Patina, die dem Objekt zusätzliche Tiefe verleiht — ein Material, das mit der Zeit schöner wird.' WHERE "id" = 6;

UPDATE "products" SET "beschreibung" = 'Das Wandregal No.7 ist aus einer einzigen, durchgehenden Altholzbohle gefertigt — ohne Stöße, ohne Klebungen. Die Bohle stammt aus einem abgebrochenen Getreidestadel und trägt die Spuren langer Arbeitsjahre: Schleifspuren, kleine Kerben und eine durch die Zeit gewachsene Tiefe der Maserung. Montiert wird es mit zwei unauffälligen Wandhalterungen aus geschwärztem Stahl, die das Regal optisch schweben lassen. Es eignet sich für Bücher, Pflanzen, Dekoobjekte und alles, was einen würdigen Platz verdient.' WHERE "id" = 7;

UPDATE "products" SET "beschreibung" = 'Der Bilderrahmen No.8 ist ein Kleinod der Holzverarbeitung. Er entstand aus Holz alter Weinreben, das nach dem Rodungsschnitt gesammelt und getrocknet wurde. Weinrebenholz ist außergewöhnlich dicht, hart und zeigt eine feine, fast skulpturale Maserung mit cremefarbenen und dunkelbraunen Tönen. Das Format 20 × 30 cm eignet sich für Fotos, Aquarelle oder Zeichnungen. Die Rückwand ist aus Sperrholz, das Glas entspiegelt. Auf Wunsch auch in anderen Formaten erhältlich.' WHERE "id" = 8;

UPDATE "products" SET "beschreibung" = 'Der Spiegel No.9 verbindet Funktion und Handwerk zu einem Möbelstück mit Charakter. Der Rahmen ist aus Scheunenholz gefertigt — alten Brettern, die jahrzehntelang Wind und Wetter ausgesetzt waren und dabei eine silbrig-braune Oberfläche entwickelt haben. Das Spiegelglas ist bis zum inneren Rahmenrand geführt, was dem Spiegel eine großzügige Wirkung verleiht. Eine Aufhängung für horizontale und vertikale Montage ist bereits integriert. Für Flur, Schlafzimmer und Bäder.' WHERE "id" = 9;

UPDATE "products" SET "beschreibung" = 'Dieser Kerzenhalter entstand aus einem mächtigen Eichenbalken, der beim Abriss eines alten Presshauses in Klosterneuburg geborgen wurde. Für drei Kerzen unterschiedlicher Größe gefräst, zeigt er die volle Schönheit des dichten Eichenholzes mit seinen markanten Jahresringen. Die Kerzenaufnahmen sind mit Metallhülsen ausgekleidet, um das Holz vor Wachs zu schützen. Das Objekt funktioniert als Tischkerzensteg, aber auch als Wanddekoration — auf der Rückseite sind zwei Aufhänger integriert.' WHERE "id" = 10;

UPDATE "products" SET "beschreibung" = 'Die Wanduhr No.11 besteht aus einer gesägten Querscheibe eines alten Kirschbaums. Die konzentrischen Jahresringe, die markante Kernholzfärbung von tiefem Rotbraun bis cremig-weiß und die natürlichen Risse am Rand machen jedes Stück zu einem absoluten Unikat. Das lautlose Uhrwerk (Sweep-Mechanismus) verhindert das typische Ticken. Die Ziffern sind als schlichte Messingpunkte ausgeführt, die sich dezent in das natürliche Bild der Holzscheibe einfügen.' WHERE "id" = 11;

UPDATE "products" SET "beschreibung" = 'Das Tablett No.12 ist aus zwei verschiedenen Altholzarten zusammengesetzt — helles Ahornholz und dunkles Nussholz wechseln sich in breiten Streifen ab und ergeben ein lebendiges Muster ohne künstliche Bemalung. Die seitlichen Griffleisten sind aus massivem Stahl geschmiedet und patiniert, was dem Tablett ein industrielles, dabei warmes Erscheinungsbild verleiht. Die Oberfläche ist lebensmittelecht geölt und eignet sich für Speisen, Getränke und Dekoarrangements.' WHERE "id" = 12;

UPDATE "products" SET "beschreibung" = 'Der Hocker No.13 ist kein Möbelstück, das sich versteckt — er ist ein Objekt mit Präsenz. Die Sitzfläche ist aus einer massiven, 6 cm starken Altholzbohle gefertigt, die Beine aus quadratischen Eichenvierkant-Kanthölzern alter Herkunft. Die Oberfläche ist mit Hartöl behandelt und widersteht täglicher Beanspruchung. Der Hocker trägt problemlos 120 kg, eignet sich als Sitzgelegenheit, Beistelltisch oder Pflanzensockel. Kein Span, kein Leim, kein Furnier — nur massives Holz.' WHERE "id" = 13;

UPDATE "products" SET "beschreibung" = 'Der Pflanzenständer No.14 ist dreistufig aufgebaut und ermöglicht es, Pflanzen auf verschiedenen Ebenen zu präsentieren. Die Latten sind aus altem Obstholz gefertigt, das seinen lebhaften Charakter durch unterschiedliche Rostfarben von Orange bis Dunkelbraun zeigt. Jede Stufe ist in ihrer Breite etwas unterschiedlich, was dem Gestell ein organisches, gewachsenes Erscheinungsbild gibt. Für Balkone und Innenräume geeignet, ideal für kleine Kräutergärten oder Sukkulenten-Arrangements.' WHERE "id" = 14;

UPDATE "products" SET "beschreibung" = 'Das Weinregal No.15 ist aus alten Weinfass-Dauben gefertigt — jenen gebogenen Holzlatten, die das Fass formen und dem Wein seinen Charakter mitgeben. Das Eichenholz, das jahrelang in Kontakt mit Wein war, zeigt tiefe Brauntöne und einen leicht würzigen Duft, der noch lange erhalten bleibt. Sechs Flaschen werden waagrecht gelagert und sind von beiden Seiten sichtbar. Die Wandmontage ist mit zwei Haken simpel und sicher. Ein besonderes Geschenk für Weinliebhaber.' WHERE "id" = 15;

UPDATE "products" SET "beschreibung" = 'Der Schreibtisch-Organizer No.16 ist ein kompakter Helfer mit großem Charakter. Drei Fächer für Dokumente, Briefe und Notizbücher sowie ein runder Stiftehalter sind aus einem einzigen Stück Altholz herausgearbeitet — die Verbindungen sind als Zinken ausgeführt, eine der ältesten und stabilsten Holzverbindungen überhaupt. Die raue, unbehandelte Innenseite der Fächer sorgt dafür, dass Papier nicht verrutscht. Für jeden Schreibtisch, der nach mehr Persönlichkeit verlangt.' WHERE "id" = 16;

UPDATE "products" SET "beschreibung" = 'Das Türschild No.17 ist aus einer runden Querscheibe gefertigt — ein ganzer Baum, in einer Scheibe eingefangen. Jahresringe, Kernspalten und die natürliche Form des Stammes bleiben vollständig erhalten. Auf der glatten Vorderseite kann auf Wunsch ein Name, eine Hausnummer oder ein Zitat eingraviert werden. Die Rückseite trägt eine Lasche für die einfache Türmontage. Ein Stück Natur, das dem Eingang Ihres Hauses oder Ihrer Wohnung ein unverwechselbares Gesicht gibt.' WHERE "id" = 17;

UPDATE "products" SET "beschreibung" = 'Der Briefhalter No.18 verbindet zwei unterschiedliche Altholzarten — ein helles und ein dunkles Holz — zu einem eleganten Kontrast auf dem Schreibtisch. Drei geschwungene Vintage-Messinghaken halten Briefe, Karten, Fotos und Merkzettel griffbereit. Das Holz ist mit einem matten Hartwachsöl behandelt, das die natürliche Maserung betont. Das Objekt kann auch als Schlüsselbrett an der Wand montiert werden. Kleines Stück, große Wirkung.' WHERE "id" = 18;

UPDATE "products" SET "beschreibung" = 'Das Schneidebrett No.19 ist aus massiver Altholz-Eiche gefertigt — einer der härtesten und strapazierfähigsten heimischen Holzarten. Die großzügige Schneidfläche bietet Platz für Gemüse, Käse und Brot. Eine eingefräste Saftrille verhindert, dass Flüssigkeiten den Tisch erreichen. Der Griff ist aus dem gleichen Holz herausgearbeitet, ohne Klebungen oder Verbindungen. Die Oberfläche ist mit lebensmittelechtem Olivenöl behandelt und kann bei Bedarf nachgeölt werden.' WHERE "id" = 19;

UPDATE "products" SET "beschreibung" = 'Der Blumenkasten No.20 ist aus alten Schiffsplanken gefertigt — Holz, das auf dem Wasser war, die Witterung kennt und Feuchte gewohnt ist. Die natürlichen Salzspuren und Verfärbungen des Meeresholzes verleihen dem Kasten einen einzigartigen Charakter. Innen ist er mit einer robusten Teichfolie ausgelegt, die Erde und Feuchtigkeit zuverlässig zurückhält. Geeignet für Balkon, Terrasse und Fensterbrett. Ideal für Kräuter, Sommerblumen und kleine Gemüsepflanzen.' WHERE "id" = 20;

UPDATE "products" SET "beschreibung" = 'Die Garderobenleiste No.21 ist aus einer durchgehenden Altholzbohle gefertigt, die über ihre gesamte Länge von vier handgeschmiedeten Haken begleitet wird. Die Haken sind aus Flachstahl einzeln geschmiedet, gebogen und geschwärzt — jeder in seiner Form minimal unterschiedlich. Das Holz ist geölt und zeigt eine lebhafte Maserung mit hellen und dunklen Bereichen. Für Flure, Schlafzimmer, Kinderzimmer und Küchen. Auf Wunsch auch mit mehr Haken oder größerer Länge.' WHERE "id" = 21;

UPDATE "products" SET "beschreibung" = 'Das Schaukelbrett No.22 ist aus einer mächtigen, alten Eichenbohle gefertigt — dem Holz, das in Mitteleuropa für seine außergewöhnliche Festigkeit, Langlebigkeit und Schönheit bekannt ist. Die Bohle wurde sorgfältig getrocknet, von Hand geschliffen und mit Hartöl behandelt. Das naturfarbene Hanfseil ist dreifach geflochten und für eine Traglast von deutlich über 100 kg ausgelegt. Die Deckenbefestigung erfolgt mit geprüften Stahlhaken und Karabinern. Ein Schaukelbrett, das Generationen übersteht.' WHERE "id" = 22;
